services:
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  mariadb:
    image: 'mysql:lts'
    environment:
      - 'MYSQL_DATABASE=blur'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=blurr123'
      - 'MYSQL_USER=blur'
    ports:
      - "3306:3306"